# Project-wide Gradle settings
# https://docs.gradle.org/current/userguide/build_environment.html

# Increase JVM heap for larger projects
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8

# Enable Gradle configuration cache for faster builds
org.gradle.configuration-cache=true

# Android
android.useAndroidX=true
android.enableJetifier=false

# Kotlin
kotlin.code.style=official

# KSP
ksp.incremental=false

# Non-transitive R classes for faster builds
android.nonTransitiveRClass=true
